### PR TITLE
Make compatible with Haml >= 3.1, add a translatable string extractions task

### PR DESCRIPTION
**Pull request by potager**

### CODE REVIEW

**Comment by nu7hatch** [comment]
Hello, thanks for your commitment! Unfortunately I am not maintaining this gem anymore, this was just an experiment which actually failed, I am not  using haml at all in my work :P. If you like I could give you push access to the repo.

-nu7

**Comment by potager** [comment]
Well, your experiment worked fine for me. :)  If you are not interested in maintaining the gem anymore, I could probably go on with that part. More than push access to the repo, I'll be interested in the ability to update what's on rubygems.org. Thanks!

**Comment by nu7hatch** [comment]
Yeah, sure, give me your handles on rubygems, i will give you access to everything.

**Comment by potager** [comment]
Thanks a lot! Handle on rubygems is “potager” like here. I'll probably update the gemspec and publish what's in that request under 0.3.0.

**Comment by nu7hatch** [comment]
I gave you commit access to the repo. Um but i need your email to give you gem ownership, send it to me on priv or to my mail.

**Comment by potager** [comment]
I have sent you several emails already about the gem ownership without a reply so far. So let's try one more time here.

The account on rubygems.org is `potager` and the associated email is `jardiniers` at `potager.org`.

The extra question being: if you are not interested in maintaining haml-magic-translations anymore, maybe it would be better to have our repository as the main one?

**Comment by nu7hatch** [comment]
@potager um, i found ur mail in spam. anyway, added you now to the owners.

**Pull request closed without merging**
